;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Dec 6 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

;port adresleri 100h,102h,104h,106h
START:
        MOV AL,82H ;controlword		1000 x01x ->x=0 
        MOV DX,106H;control
        OUT DX,AL

        MOV AL,0FFH 
        MOV DX,100H;portA
        OUT DX,AL

ENDLESS:

        MOV DX,102H       ; input alma(portB)
        IN  AL,DX

        CMP AL,0FFH       ; input yok
        JE  ENDLESS

        MOV DX,100H       ; output(portA)

	
        CMP AL,0FEH       ;buton0	1111 1110
        JNE B1
        MOV AL,0C0H       ;0	1100 0000
        OUT DX,AL
        JMP ENDLESS

B1:     CMP AL,0FDH       ;buton1	1111 1101
        JNE B2
        MOV AL,0F9H       ;1	1111 1001
        OUT DX,AL
        JMP ENDLESS

B2:     CMP AL,0FBH       ;buton2	1111 1011
        JNE B3
        MOV AL,0A4H       ;2	1010 0100
        OUT DX,AL
        JMP ENDLESS

B3:     CMP AL,0F7H       ;buton3	1111 0111
        JNE B4
        MOV AL,0B0H       ;3	1011 0000
        OUT DX,AL
        JMP ENDLESS

B4:     CMP AL,0EFH       ;buton4	1110 1111
        JNE B5
        MOV AL,99H       ;4	1001 1001
        OUT DX,AL
        JMP ENDLESS

B5:     CMP AL,0DFH       ;buton5	1101 1111
        JNE B6
        MOV AL,92H       ;5	1001 0010
        OUT DX,AL
        JMP ENDLESS

B6:     CMP AL,0BFH       ;buton6	1011 1111
        JNE B7
        MOV AL,82H       ;6	1000 0010
        OUT DX,AL
        JMP ENDLESS

B7:     CMP AL,7FH       ;buton7	0111 1111
        JNE ENDLESS
        MOV AL,0F8H       ;7	1111 1000
        OUT DX,AL

        JMP ENDLESS

CODE ENDS
END START
